//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKQ.Domain.RoboAI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoboAI.IRoboAI")]
    public interface IRoboAI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoboAI/GetBid", ReplyAction="http://tempuri.org/IRoboAI/GetBidResponse")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        string GetBid(string gameState, string conventionCard, string seat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoboAI/GetCard", ReplyAction="http://tempuri.org/IRoboAI/GetCardResponse")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        string GetCard(string gameState, string conventionCard, string seat, int quality, int time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoboAI/ExplainBid", ReplyAction="http://tempuri.org/IRoboAI/ExplainBidResponse")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        string ExplainBid(string gameState, string conventionCard, int bidIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoboAI/ClaimOk", ReplyAction="http://tempuri.org/IRoboAI/ClaimOkResponse")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        bool ClaimOk(string gameState, string conventionCard, string seat, int tricksForMe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoboAI/PossibleBids", ReplyAction="http://tempuri.org/IRoboAI/PossibleBidsResponse")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        AKQ.Domain.RoboAI.ArrayOfString PossibleBids(string gameState, string conventionCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoboAI/DoubleDummy_Tricks", ReplyAction="http://tempuri.org/IRoboAI/DoubleDummy_TricksResponse")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        int DoubleDummy_Tricks(string gameState, string declarer, string trumpSuit);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoboAIChannel : AKQ.Domain.RoboAI.IRoboAI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoboAIClient : System.ServiceModel.ClientBase<AKQ.Domain.RoboAI.IRoboAI>, AKQ.Domain.RoboAI.IRoboAI {
        
        public RoboAIClient() {
        }
        
        public RoboAIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoboAIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoboAIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoboAIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetBid(string gameState, string conventionCard, string seat) {
            return base.Channel.GetBid(gameState, conventionCard, seat);
        }
        
        public string GetCard(string gameState, string conventionCard, string seat, int quality, int time) {
            return base.Channel.GetCard(gameState, conventionCard, seat, quality, time);
        }
        
        public string ExplainBid(string gameState, string conventionCard, int bidIndex) {
            return base.Channel.ExplainBid(gameState, conventionCard, bidIndex);
        }
        
        public bool ClaimOk(string gameState, string conventionCard, string seat, int tricksForMe) {
            return base.Channel.ClaimOk(gameState, conventionCard, seat, tricksForMe);
        }
        
        public AKQ.Domain.RoboAI.ArrayOfString PossibleBids(string gameState, string conventionCard) {
            return base.Channel.PossibleBids(gameState, conventionCard);
        }
        
        public int DoubleDummy_Tricks(string gameState, string declarer, string trumpSuit) {
            return base.Channel.DoubleDummy_Tricks(gameState, declarer, trumpSuit);
        }
    }
}
